# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rpm', models.IntegerField()),
                ('inj1', models.IntegerField()),
                ('inj2', models.IntegerField()),
                ('ign1', models.IntegerField()),
                ('ign2', models.IntegerField()),
                ('wtemp', models.IntegerField()),
                ('airtemp', models.IntegerField()),
                ('airp', models.IntegerField()),
                ('oilt', models.IntegerField()),
                ('tps', models.IntegerField()),
                ('lambda_1', models.IntegerField()),
                ('lambda_trg', models.IntegerField()),
                ('speed_fl', models.IntegerField()),
                ('speed_fr', models.IntegerField()),
                ('speed_rl', models.IntegerField()),
                ('speed_rr', models.IntegerField()),
                ('vbatt', models.IntegerField()),
                ('aux', models.IntegerField()),
                ('det', models.IntegerField()),
                ('fcmp', models.IntegerField()),
                ('ecu_error', models.IntegerField()),
                ('fpga_error', models.IntegerField()),
                ('status', models.IntegerField()),
                ('delta', models.IntegerField()),
                ('dwell', models.IntegerField()),
                ('map_tc_sel', models.IntegerField()),
                ('slpf_fl', models.IntegerField()),
                ('slpf_fr', models.IntegerField()),
                ('slpf_rl', models.IntegerField()),
                ('slpf_rr', models.IntegerField()),
                ('cutoff', models.IntegerField()),
                ('time', models.IntegerField()),
                ('aux_data1', models.IntegerField()),
                ('aux_data2', models.IntegerField()),
                ('aux_data3', models.IntegerField()),
                ('aux_data4', models.IntegerField()),
                ('aux_data5', models.IntegerField()),
                ('aux_data6', models.IntegerField()),
                ('aux_data7', models.IntegerField()),
                ('aux_data8', models.IntegerField()),
                ('aux_data9', models.IntegerField()),
                ('aux_data10', models.IntegerField()),
                ('aux_data11', models.IntegerField()),
                ('aux_data12', models.IntegerField()),
                ('aux_data13', models.IntegerField()),
                ('aux_data14', models.IntegerField()),
                ('aux_data15', models.IntegerField()),
                ('aux_data16', models.IntegerField()),
                ('aux_data17', models.IntegerField()),
                ('aux_data18', models.IntegerField()),
                ('aux_data19', models.IntegerField()),
                ('aux_data20', models.IntegerField()),
                ('aux_data21', models.IntegerField()),
                ('aux_data22', models.IntegerField()),
                ('aux_data23', models.IntegerField()),
                ('aux_data24', models.IntegerField()),
                ('aux_data25', models.IntegerField()),
                ('aux_data26', models.IntegerField()),
                ('aux_data27', models.IntegerField()),
                ('aux_data28', models.IntegerField()),
                ('aux_data29', models.IntegerField()),
                ('aux_data30', models.IntegerField()),
                ('aux_data31', models.IntegerField()),
                ('aux_data32', models.IntegerField()),
            ],
        ),
    ]
