# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='owner',
        ),
    ]
